# Global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "gesture-api"

# Scrape configs
scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 5s
    metrics_path: /metrics

  # Hand Gesture API monitoring
  - job_name: "gesture-api"
    static_configs:
      - targets: ["api:8080"]
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 10s